# Generated by Django 5.2.1 on 2025-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccUsers',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=100)),
            ],
            options={
                'db_table': 'acc_users',
            },
        ),
        migrations.CreateModel(
            name='TbItemMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=15, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=60, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate4', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate5', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate6', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate7', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tb_item_master',
            },
        ),
    ]
